export const word01 = [
    "à fond",
    "à la grecque",
    "a posteriori",
    "ab aeterno",
    "abaculus",
    "abraum",
    "acacia",
    "accordatura",
    "acerola",
    "acetaminophen",
    "acetone",
    "acharya",
    "Achernar",
    "acicula",
    "acidophilus",
    "acoel",
    "acrogeria",
    "acropachy",
    "ad nauseam",
    "adiabatic",
    "adieu",
    "adscititious",
    "Aegilops",
    "aegrotat",
    "aerophilatelic",
    "aes rude",
    "Aesir",
    "affiche",
    "ageusia",
    "agitprop",
    "Aglaia",
    "agrypnia",
    "ague",
    "ahimsa",
    "ahuatle",
    "Ahuehuete",
    "Ahura Mazda",
    "ailette",
    "aistopod",
    "Aitutakian",
    "ajimez",
    "akaryote",
    "akkum",
    "alate",
    "alcarraza",
    "Alfvén",
    "alleluiatic",
    "allochroous",
    "almuerzo",
    "alouatte",
    "alpargata",
    "altazimuth",
    "amaryllis",
    "amour propre",
    "amphistylar",
    "amuse-gueule",
    "anabathmoi",
    "anaphylaxis",
    "anathema",
    "ancien régime",
    "andouille",
    "anemone",
    "angiitis",
    "aniseikonia",
    "Anno Hegirae",
    "anomaliped",
    "anosognosia",
    "antenatus",
    "Antigua",
    "Apabhramsa",
    "ape-ape",
    "aperçu",
    "aphasia",
    "Apistogramma",
    "apocryphal",
    "apophyge",
    "Apostolici",
    "Appaloosa",
    "appetitost",
    "après",
    "Aramaic",
    "Ardhamagadhi",
    "Ardipithecus",
    "ardoise",
    "arenaceous",
    "aretalogy",
    "as nas",
    "ascites",
    "astaxanthin",
    "Asura",
    "asylee",
    "attacca",
    "au bleu",
    "au courant",
    "au jus",
    "avgolemono",
    "azotea",
    "azulejo",
];

export const word02 = ["baccate", "bagwyn", "bahr", "bahuvrihi", "bailiwick", "balata", "balbriggan", "baleen", "banh mi", "Barnumesque", "Bartókian", "Barylambda", "bas-relief", "batamote", "battue", "Baucis", "bauxite", "bavardage", "Beauceron", "beaumontage", "Beaux arts", "beccafico", "Bêche-de-Mer", "becquerel", "ben trovato", "Beowulf", "berceuse", "bergère", "Bernoulli effect", "bêtise", "betony", "beurre", "Bezier curve", "bhangra", "bhikshuni", "bibelot", "bibimbap", "bisbigliando", "bismillah", "blatherskite", "blottesque", "bobolink", "Boise", "Bolognese", "boniface", "bordereaux", "Bosc", "bouclé", "boudin", "bouillon", "boulevardier", "boutade", "boutonniere", "bozzetto", "Braeburn", "brouhaha", "brume", "bruschetta", "buccal", "buñuelo", "Bunyanesque", "Burkinabe", "cabochon", "ca’canny", "cacaxte", "cachexia", "cacoëthes", "Caerphilly", "cahiers", "caique", "cairn", "caisson", "calabash", "calamondin", "calligram", "caló", "calusar", "calvities", "camarilla", "Camembert", "canaille", "cantatrice", "caprifig", "Caracas", "carcajou", "carrageenan", "carrageenin", "carragheenin", "Carrickmacross", "cartouches", "caryatid", "Casimir effect", "Castalia", "catachresis", "cataphora", "catarrh", "catjang", "cavalletti", "caveola", "cephalopod", "cermet", "chalaza", "Chalcolithic", "champignon", "Charon", "chastushka", "chasuble", "cheongsam", "chèvre", "chicanery", "chopine", "chorten", "choucroute", "ciénaga", "cienega", "ciliopathy", "cioppino", "cire perdue", "cirri", "clerihew", "cobalamin", "coccygeal", "colcannon"]

export const word03 = ["colloque", "colporteur", "colubrine", "concatenate", "connoisseur", "consanguine", "consigliere", "consommé", "contrapposto", "contretemps", "copernicium", "corrigenda", "corybantic", "coterie", "cotoneaster", "coulibiac", "coulisse", "coulrophobia", "coup de grace", "courgette", "couverture", "creances", "crokinole", "croquembouche", "croquignole", "croustade", "cryptozoa", "cushag", "cynocephali", "daguerreotype", "Darjeeling", "darmstadtium", "de rigueur", "decastich", "degauss", "Deimos", "Delmarva Peninsula", "demitasse", "démodé", "demurrage", "Déné", "dengue", "dentifrice", "derring-do", "Deseret", "desiccate", "Devanagari", "dghaisa", "dhole", "dhurrie", "diapason", "diaphanous", "diastole", "Djibouti", "dragée", "drahthaar", "Dubhe", "Dubuque", "duello", "duxelles", "dvandva", "Dvorak", "dysphasia", "dysrhythmia", "ecchymosis", "echelon", "echinoderm", "edamame", "effete", "effleurage", "Egeria", "eisteddfod", "élan", "eleemosynary", "eluate", "embouchure", "emollient", "emolument", "emphysema", "ennui", "Enoch Arden", "enoki", "epideictic", "epistemology", "epixylous", "Equatoguinean", "Erewhonian", "Eris", "erythroblast", "Esau", "escarole", "escheator", "esclandre", "escritoire", "espadrille", "espalier", "espial", "esplanade", "estancia", "estovers", "estrepe", "ethylene", "étouffée", "eudiometer", "Euroclydon", "exchequer", "farfalle", "farouche", "farrago", "fatshedera", "fauchard", "Feldenkrais", "fellahin", "fêng shui", "ferruginous", "fête champêtre", "fetticus", "fibromyalgia", "Firbolg", "flehmen", "force majeure", "Formica", "foudroyant", "frabjous", "fracas", "funori", "furan", "Furneaux", "furuncle", "gabarit", "gabbro"]

export const word04 = ["gaffe", "gagaku", "Gaia", "gaillardia", "Galahad", "galatea", "galena", "gallivat", "galoot", "gambol", "Gaspesian", "gasthaus", "gattine", "Geatish", "gegenschein", "gendarme", "genet", "gesellschaft", "giallolino", "ginglymus", "Gippsland", "glabella", "glacis", "glengarry", "glyceraldehyde", "goanna", "Gondwana", "graywacke", "griot", "Groenendael", "Gruyère", "guan", "guapena", "Guarnerius", "guayabera", "guerite", "guichet", "Guidonian", "Gurmukhi", "gyascutus", "gyokuro", "gypsophila", "gypsum", "halala", "halcyon", "Hamtramck", "hangul", "haupia", "hebdomadal", "Hebrides", "hei-tiki", "hellebore", "hemorrhage", "henotheism", "hepatectomy", "Herodotean", "hiortdahlite", "Hippolyta", "hirsute", "hoi polloi", "holobenthic", "hominin", "homoscedasticity", "hordeolum", "hsaing-waing", "Hsia", "Huallaga", "huerta", "Humboldt", "hutia", "hypaethral", "hyssop", "hysteresis", "hysteron proteron", "ichthyology", "icosahedron", "ikat", "ikebana", "immie", "in medias res", "in silico", "incunabula", "inglenook", "ingot", "insouciance", "integument", "internecine", "interregnum", "Inugsuk", "Inuk", "isagoge", "Ishihara test", "isosceles", "ivermectin", "jai alai", "jalousie", "janthina", "jasmone", "je ne sais quoi", "jerboa", "joropo", "Jumada", "Jungian", "kakapo", "kaleidoscope", "kalimba", "kalopanax", "Kannada", "kapparah", "katakana", "katana", "kathakali"]

export const word05 = ["kepi", "Keplerian", "kerril", "Keynesian", "kichel", "kipuka", "Kitksan", "kiva", "Kjeldahl", "kobold", "koh-i-noor", "Koine", "koji", "korrigan", "krewe", "kriegspiel", "Kuiper Belt", "kwashiorkor", "kyphoplasty", "La Tène", "laccolith", "lanceolate", "langrage", "laterigrade", "Latinxua", "lebensraum", "leberwurst", "lebkuchen", "lecithin", "lefse", "lierre", "ligas", "lilliputian", "limaçon", "Llullaillaco", "lobscouse", "loess", "logothete", "lokelani", "louche", "loupe", "luftmensch", "lunulae", "macaque", "macchiato", "macigno", "mackinaw", "macushla", "mademoiselle", "maillot", "majuscule", "Makgadikgadi Pans", "malaise", "Mandelbrot set", "mandorla", "mandragora", "mange-tout", "mangonel", "Manu", "maquillage", "Marathi", "marcel", "marcescent", "maringouin", "martinoe", "mascarpone", "mässig", "mediobrome", "medulla", "megacephalic", "megrims", "meiosis", "mele", "mellifluous", "Menaia", "meringue", "Metonic cycle", "microfiche", "millegrain", "Mirach", "miscible", "mittimus", "moiety", "mondegreen", "MOOC", "moraine", "moribund", "morion", "mortadella", "motherumbung", "mozo", "muesli", "mufti", "muktuk", "muliebrity", "Muzak", "myeloma", "Nabal", "nacelle", "nahcolite", "naïveté", "naricorn", "Naugahyde", "naumachia", "neem", "neophyte", "Ner Tamid", "nescience", "Nethinim", "Nicoise", "nictitate", "nidicolous", "nimiety", "niminy-piminy", "nisi", "nival", "ni-Vanuatu", "niveau", "nodosity", "nonpareil", "notturno", "noumenon", "nouveau", "Novanglian", "nudibranch", "nyctinasty", "obeisant", "odontiasis", "oeuvre", "ogival"]