export const word01 = [
    "à fond",
    "à la grecque",
    "a posteriori",
    "ab aeterno",
    "abaculus",
    "abraum",
    "acacia",
    "accordatura",
    "acerola",
    "acetaminophen",
    "acetone",
    "acharya",
    "Achernar",
    "acicula",
    "acidophilus",
    "acoel",
    "acrogeria",
    "acropachy",
    "ad nauseam",
    "adiabatic",
    "adieu",
    "adscititious",
    "Aegilops",
    "aegrotat",
    "aerophilatelic",
    "aes rude",
    "Aesir",
    "affiche",
    "ageusia",
    "agitprop",
    "Aglaia",
    "agrypnia",
    "ague",
    "ahimsa",
    "ahuatle",
    "Ahuehuete",
    "Ahura Mazda",
    "ailette",
    "aistopod",
    "Aitutakian",
    "ajimez",
    "akaryote",
    "akkum",
    "alate",
    "alcarraza",
    "Alfvén",
    "alleluiatic",
    "allochroous",
    "almuerzo",
    "alouatte",
    "alpargata",
    "altazimuth",
    "amaryllis",
    "amour propre",
    "amphistylar",
    "amuse-gueule",
    "anabathmoi",
    "anaphylaxis",
    "anathema",
    "ancien régime",
    "andouille",
    "anemone",
    "angiitis",
    "aniseikonia",
    "Anno Hegirae",
    "anomaliped",
    "anosognosia",
    "antenatus",
    "Antigua",
    "Apabhramsa",
    "ape-ape",
    "aperçu",
    "aphasia",
    "Apistogramma",
    "apocryphal",
    "apophyge",
    "Apostolici",
    "Appaloosa",
    "appetitost",
    "après",
    "Aramaic",
    "Ardhamagadhi",
    "Ardipithecus",
    "ardoise",
    "arenaceous",
    "aretalogy",
    "as nas",
    "ascites",
    "astaxanthin",
    "Asura",
    "asylee",
    "attacca",
    "au bleu",
    "au courant",
    "au jus",
    "avgolemono",
    "azotea",
    "azulejo",
];
