const v1Words = [
    { "word": "aioli", "type": "noun", "definition": "garlic mayonnaise.", "pronunciation": "ay-oh-lee" },
    { "word": "bouffant", "type": "adjective", "definition": "voluminous.", "pronunciation": "boo-fahnt" },
    { "word": "cantankerous", "type": "adjective", "definition": "grumpy and argumentative.", "pronunciation": "kan-tang-kuh-rus" },
    { "word": "dromic", "type": "adjective", "definition": "of, relating to, or in the form of a racecourse.", "pronunciation": "droh-mik" },
    { "word": "ermine", "type": "noun", "definition": "any of several weasels that have white fur in winter.", "pronunciation": "er-min" },
    { "word": "frazil", "type": "noun", "definition": "ice crystals sometimes similar to slush that are formed in turbulent water.", "pronunciation": "fray-zil" },
    { "word": "gratis", "type": "adverb", "definition": "without charge : free.", "pronunciation": "grah-tis" },
    { "word": "heptad", "type": "noun", "definition": "a group of seven people or things.", "pronunciation": "hep-tad" },
    { "word": "incisiform", "type": "adjective", "definition": "having the form of a tooth adapted for cutting.", "pronunciation": "in-sy-zuh-form" },
    { "word": "jubilant", "type": "adjective", "definition": "expressing gladness or triumphant joy.", "pronunciation": "joo-buh-lunt" },
    { "word": "koto", "type": "noun", "definition": "a long Japanese zither having 13 silk strings.", "pronunciation": "koh-toh" },
    { "word": "locavore", "type": "noun", "definition": "a person who eats foods grown nearby whenever possible.", "pronunciation": "loh-kuh-vor" },
    { "word": "myopic", "type": "adjective", "definition": "lacking in foresight or keenness of insight.", "pronunciation": "my-oh-pik" },
    { "word": "nomancy", "type": "noun", "definition": "divination by letters.", "pronunciation": "noh-man-see" },
    { "word": "obstreperous", "type": "adjective", "definition": "stubborn and defiant often with a show of noisy disorder.", "pronunciation": "ob-strep-uh-rus" },
    { "word": "panary", "type": "adjective", "definition": "related to breadmaking.", "pronunciation": "pan-uh-ree" },
    { "word": "quiddity", "type": "noun", "definition": "the ultimate form or the essential nature of something.", "pronunciation": "kwid-uh-tee" },
    { "word": "regurgitate", "type": "verb", "definition": "to bring, forcefully impel, or pour back out again.", "pronunciation": "ree-gur-juh-tayt" },
    { "word": "smellfungus", "type": "noun", "definition": "someone who tends to find fault in others.", "pronunciation": "smel-fung-gus" },
    { "word": "tommyrot", "type": "noun", "definition": "complete foolishness or nonsense.", "pronunciation": "tom-ee-rot" },
    { "word": "ulna", "type": "noun", "definition": "the inner of the two bones of the forearm.", "pronunciation": "ul-nuh" },
    { "word": "Vulcan", "type": "noun", "definition": "a worker in metals; especially: a blacksmith.", "pronunciation": "vul-kan" },
    { "word": "widdershins", "type": "adverb", "definition": "counterclockwise.", "pronunciation": "wid-der-shinz" },
    { "word": "yabbies", "type": "plural noun", "definition": "small burrowing crayfish that live in most Australian creeks and water holes.", "pronunciation": "yab-eez" },
    { "word": "zurna", "type": "noun", "definition": "a traditional Middle Eastern woodwind instrument.", "pronunciation": "zur-nuh" },
    { "word": "avgolemono", "type": "noun", "definition": "a chicken soup made with egg yolks and lemon juice.", "pronunciation": "ahv-goh-leh-moh-noh" },
    { "word": "bobolink", "type": "noun", "definition": "a small American songbird that resembles the blackbird.", "pronunciation": "boh-boh-link" },
    { "word": "creances", "type": "plural noun", "definition": "fine lines used to leash a hawk during training.", "pronunciation": "kree-uhns-iz" },
    { "word": "Dvorak", "type": "noun", "definition": "a typing keyboard with frequently used letters placed centrally.", "pronunciation": "dvor-zhak" },
    { "word": "eisteddfod", "type": "noun", "definition": "a Welsh competitive festival of the arts especially in singing.", "pronunciation": "eye-steth-vod" },
    { "word": "Firbolg", "type": "plural noun", "definition": "an ancient group of people in Ireland.", "pronunciation": "fur-bolg" },
    { "word": "giallolino", "type": "noun", "definition": "any of a variety of yellow pigments.", "pronunciation": "jah-loh-lee-noh" },
    { "word": "hoi polloi", "type": "plural noun", "definition": "ordinary people : multitude, masses.", "pronunciation": "hoy puh-loy" },
    { "word": "Inuk", "type": "noun", "definition": "a member of the Inuit people.", "pronunciation": "ee-nook" },
    { "word": "Jumada", "type": "noun", "definition": "either of two two months of the Islamic year.", "pronunciation": "joo-mah-duh" },
    { "word": "kerril", "type": "noun", "definition": "an Asiatic sea snake.", "pronunciation": "kehr-il" },
    { "word": "leberwurst", "type": "noun", "definition": "liver sausage.", "pronunciation": "lay-ber-wurst" },
    { "word": "moraine", "type": "noun", "definition": "a collection of earth and stones carried and finally deposited by a glacier.", "pronunciation": "muh-rayn" },
    { "word": "niminy-piminy", "type": "adjective", "definition": "absurdly nice : ridiculously delicate : finicky.", "pronunciation": "nim-in-ee pim-in-ee" },
    { "word": "ormolu", "type": "noun", "definition": "brass made to imitate gold and used for furniture and other decorative purposes.", "pronunciation": "or-muh-loo" },
    { "word": "porwigle", "type": "noun", "definition": "a tadpole.", "pronunciation": "por-wig-gul" },
    { "word": "quokka", "type": "noun", "definition": "a small, stocky wallaby with a reddish-brown coat and a short tail.", "pronunciation": "kwok-uh" },
    { "word": "redingote", "type": "noun", "definition": "a lightweight woman’s coat that is belted with the front open.", "pronunciation": "red-ing-goht" },
    { "word": "svarabhakti", "type": "noun", "definition": "the introduction of a vowel sound in Sanskrit especially between r or l and a following consonant.", "pronunciation": "svah-rah-bhak-tee" },
    { "word": "tullibee", "type": "noun", "definition": "a whitefish of central and northern North America.", "pronunciation": "tul-uh-bee" },
    { "word": "unakite", "type": "noun", "definition": "an opaque igneous rock flecked with green, black, pink, and white that is used as a gemstone.", "pronunciation": "yoo-nuh-kyt" },
    { "word": "vexillologist", "type": "noun", "definition": "a specialist in the study of flags.", "pronunciation": "vek-sil-ol-uh-jist" },
    { "word": "Wensleydale", "type": "noun", "definition": "a white cheese that is eaten fresh prior to preserving.", "pronunciation": "wenz-lee-dayl" },
    { "word": "xyloglyphy", "type": "noun", "definition": "wood sculpting that is artistic in nature.", "pronunciation": "zy-log-luh-fee" },
    { "word": "yosenabe", "type": "noun", "definition": "a soup made of vegetables and seafood in broth.", "pronunciation": "yoh-seh-nah-beh" },
    { "word": "zugzwang", "type": "noun", "definition": "the need to make a move in chess when it is not to one’s advantage.", "pronunciation": "tsoog-tsvahng" }
];